### ISSUE TITLE
Width in html

### ISSUE THREAD

**Issue by Matthijs217** [julia-stevens/all-human-accessible-website#13]
https://github.com/julia-stevens/all-human-accessible-website/blob/1ee4e4ce1be2e8e1704d215f73eec1c97361aced/index.html#L107

probeer de styling in de CSS te houden. Dus de width in je CSS zetten

**Comment by julia-stevens** [comment]
Ik heb bewust een `width` toegevoegd aan deze afbeeldingen, zodat de HTML prettiger te lezen is. Verdere styling staat in CSS
