### ISSUE TITLE
Button gebruik

### ISSUE THREAD

**Issue by Matthijs217** [julia-stevens/all-human-accessible-website#14]
https://github.com/julia-stevens/all-human-accessible-website/blob/1ee4e4ce1be2e8e1704d215f73eec1c97361aced/index.html#L252

Je kan voor dingen met javascript beter een button gebruiken dan een anchor tag. Die zijn meer voor links.

**Comment by julia-stevens** [comment]
2c9684bd1db38c2344ab6127b402744cf8de5e18
