### ISSUE TITLE
Review Clarice & Marcin

### ISSUE THREAD

**Issue by MarsGotBars** [julia-stevens/all-human-accessible-website#16]
# Accessibility

### Kleurcontrast
- Gebruik E90166 ipv de roze kleur die je nu hebt, deze heeft namelijk een slecht contrast.

### Keyboard control
- Komt twee keer vast te zitten, een keer in de header en een keer in de player.
  - De player bevat wat linkjes die niet op beeld staan en geselecteerd kunnen worden, misschien hier iets aan doen dmv een aria attribuut

**Comment by julia-stevens** [comment]
2c9684bd1db38c2344ab6127b402744cf8de5e18
