### ISSUE TITLE
Review Ole en Dylan

### ISSUE THREAD

**Issue by DivaniNL** [julia-stevens/all-human-accessible-website#17]
De play / pause knop moet een button zijn. de rest van de a/button is top

**Comment by DivaniNL** [comment]
De image met de chevrons moeten bijvoorbeeld uitspreken (in of uitklappen), zet dit in een alt tag, of bij gebruik van svg in een aria label

**Comment by DivaniNL** [comment]
Er moet een header om de nav heen

**Comment by DivaniNL** [comment]
Het contrast is niet voldoende, bijvoorbeeld deze kleur roze: (E90166) is goed genoeg, of nog donkerder

**Comment by julia-stevens** [comment]
2c9684bd1db38c2344ab6127b402744cf8de5e18
