### ISSUE TITLE
Iris en Colin

### ISSUE THREAD

**Issue by ColindeGroot** [julia-stevens/all-human-accessible-website#18]
- je nav mag in een header element
- de programma zou in een ol kunnen i.p.v. een gezien de volgorde van programma's / dagen belangrijk zijn
- lighthouse en colormain geven aan dat de roze achtergrond niet goed past met de witte tekst. (misschien kijken voor donkere kleuren als dat kan)

**Comment by julia-stevens** [comment]
2c9684bd1db38c2344ab6127b402744cf8de5e18
